### ISSUE TITLE
Missed Crown Dropper

### ISSUE THREAD

**Issue by keyofdminer** [Noxitu/Decked-Out-2-Datapacks#1]
Missed filling the crown dropper feeding the return barrel
-547 116 1965

**Comment by keyofdminer** [comment]
It looks like rare cards are not refilling as well as the coin shop contents. Some missing contents in coin shop as well see https://www.reddit.com/r/HermitCraft/comments/18pz02q/comment/keurqnz/

**Comment by Noxitu** [comment]
Thanks - I missed crown dropper and crown shops completly as I collected droppers only from the Y level of the dungeon. :o

For the card shop, I needed to remove some randomizers that pick which cards are available - and removed right side by mistake.

I also added some other things from the thread you linked. Thanks again :-)
