### ISSUE TITLE
Missed L3 Artifact locations

### ISSUE THREAD

**Issue by keyofdminer** [Noxitu/Decked-Out-2-Datapacks#2]
Missed artifact locations

-629 -19 1920
-613 -19 1889
-603 -19 1924

**Comment by Noxitu** [comment]
I missed Googles of Symmetry in my filters - adding it added these 3 spots.

I also added today -631 -15 1987 - a dropper that opens ember shop doors for 5 minutes, that otherwise will run out after 68 successful runs.

Thanks again :-)
